apiVersion: v1
kind: ConfigMap
metadata:
  name: resqnet-config
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "resqnet.labels" . | nindent 4 }}
data:
  POSTGRES_DB:              {{ .Values.postgres.database }}
  POSTGRES_HOST:            postgres-service
  KAFKA_BOOTSTRAP_SERVERS:  kafka-service:9092
  REDIS_HOST:               redis-service
  SPRING_PROFILES_ACTIVE:   docker
  USER_SERVICE_URL:         http://user-service:{{ .Values.userService.port }}
  EMERGENCY_SERVICE_URL:    http://emergency-service:{{ .Values.emergencyService.port }}
  DISPATCH_SERVICE_URL:     http://dispatch-service:{{ .Values.dispatchService.port }}
  AI_SERVICE_URL:           http://ai-service:{{ .Values.aiService.port }}
---
apiVersion: v1
kind: Secret
metadata:
  name: resqnet-secrets
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "resqnet.labels" . | nindent 4 }}
type: Opaque
stringData:
  POSTGRES_USER:     {{ .Values.postgres.username }}
  POSTGRES_PASSWORD: {{ .Values.postgres.password }}
  JWT_SECRET:        {{ .Values.secrets.jwtSecret }}