apiVersion: v1
kind: ResourceQuota
metadata:
  name: resqnet-quota
  namespace: resqnet
spec:
  hard:
    requests.cpu:    "4"
    requests.memory: 8Gi
    limits.cpu:      "8"
    limits.memory:   16Gi
    pods:            "30"
    services:        "15"
---
apiVersion: v1
kind: LimitRange
metadata:
  name: resqnet-limits
  namespace: resqnet
spec:
  limits:
    - type: Container
      default:
        cpu:    "500m"
        memory: "512Mi"
      defaultRequest:
        cpu:    "200m"
        memory: "256Mi"
      max:
        cpu:    "2"
        memory: "2Gi"
      min:
        cpu:    "50m"
        memory: "64Mi"